<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Spotiwake</AssemblyName>
    <RootNamespace>Spotiwake</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>1.0.0</Version>
    <Authors>ggaspari</Authors>
    <Description>Impede que o Windows entre em suspensão enquanto o Spotify estiver tocando.</Description>
  </PropertyGroup>

</Project>
